### ISSUE TITLE
`undefined reference to` error when compiling demo.cc

### ISSUE THREAD

**Issue by nowaythatsok** [cms-nanoAOD/correctionlib#103] opened 2021-10-12 10:41 UTC
Dear Experts,

I am trying to make the `demo.cc` example work, but it seems like I need a bit of help. 
What I did so far:
```sh
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
python3 -m pip install correctionlib
wget https://raw.githubusercontent.com/cms-nanoAOD/correctionlib/master/src/demo.cc
g++ $(correction config --cflags --ldflags --rpath) demo.cc -o demo
```
where the last step returns some error messages:
```
tmp/ccXXTZDN.o: In function `main':
demo.cc:(.text+0x108): undefined reference to `correction::CorrectionSet::from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
demo.cc:(.text+0x336): undefined reference to `correction::Correction::evaluate(std::vector<std::variant<int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) const'
demo.cc:(.text+0x576): undefined reference to `correction::Correction::evaluate(std::vector<std::variant<int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) const'
demo.cc:(.text+0x73c): undefined reference to `correction::Correction::evaluate(std::vector<std::variant<int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) const'
```
Some extra info:
```
> g++ --version
g++ (GCC) 11.2.0
> python --version
Python 3.6.8
> correction config --cflags --ldflags --rpath
-std=c++17 -I/[...]/venv/lib64/python3.6/site-packages/correctionlib/include -L/[...]/venv/lib64/python3.6/site-packages/correctionlib/lib -lcorrectionlib -Wl,-rpath,/[...]/venv/lib64/python3.6/site-packages/correctionlib/lib
```

**Comment by nsmith-** [comment] 2021-12-17 20:58
This actually sounds a bit like the issue is coming from use of rpath: https://wiki.debian.org/RpathIssue

**Comment by nsmith-** [comment] 2021-12-17 21:02
On the other hand I have seen the exact error when I compiled correctionlib while inside cmssw environment and then tried to run it outside (because cmssw has its own gcc installation)

**Comment by nsmith-** [comment] 2022-02-08 16:50
Did you resolve your issue? I'd like to close this thread

**Comment by nsmith-** [comment] 2022-03-03 19:38
Closing due to inactivity

**Closed by nsmith-** 2022-03-03 19:38 UTC
